version: '2'

services:

  nginx:
    image: nginx:alpine
    ports:
      - 81:80
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/code
    depends_on:
      - php-fpm

  php-fpm:
    image: php:7-fpm-alpine
    volumes:
      - ./code:/code

  composer:
    image: composer
    volumes:
      - ./code:/code
    volumes:
      - ./code:/app
    command: composer install 
  
  mysql:
    image: mysql
    ports: 
      - 82:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      #- ./data/init_data/1-file.sql:/docker-entrypoint-initdb.d/1-file.sql
      #- ./data/init_data/2-another-file.gz:/docker-entrypoint-initdb.d/2-another-file.gz
      - ./data/mysql_data:/data

  mongo:
    image: mongo
    ports:
      - 83:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      #- ./data/init_data/mongo/1-file.js:/docker-entrypoint-initdb.d/1-file.js
      #- ./data/init_data/mongo/2-another-file.sh:/docker-entrypoint-initdb.d/2-another-file.sh
      - ./data/mongo_data:/data/db

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 84:15672

  #Memcached
